=== W3irdev/DAW/lenguajeMarcas/DTD/Ejercicio4/ejercicio4.dtd
<!ELEMENT videoclub (factura)>
<!ELEMENT factura (datosClientes,datosTicket)>
<!ATTLIST factura numero ID #REQUIRED>
<!ELEMENT datosClientes (nombre,primerApellido,segundoApellido,DNI,telefono*)>
<!ATTLIST datosClientes ID NMTOKEN #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT primerApellido (#PCDATA)>
<!ELEMENT segundoApellido (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT datosTicket (resguardo?,alquiler,compra)>
<!ELEMENT resguardo (formaPago,total)>
<!ELEMENT formaPago (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT alquiler (fechaDevolucion,pelicula)>
<!ELEMENT fechaDevolucion (dia,mes,anyo)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT pelicula (titulo,genero,duracion,actor+)>
<!ATTLIST pelicula id NMTOKEN #REQUIRED>
<!ATTLIST pelicula valoracion NMTOKEN #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!ELEMENT compra (DVD,cinta)>
<!ELEMENT DVD (titulo,fechaSalida)>
<!ATTLIST DVD extras ( S | N ) "N">
<!ELEMENT fechaSalida (dia,mes,anyo)>
<!ELEMENT cinta (formato)>
<!ELEMENT formato (#PCDATA)>
<!ATTLIST formato rebobinado NMTOKEN #REQUIRED>

=== W3irdev/DAW/lenguajeMarcas/DTD/Ejercicio4/ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE videoclub SYSTEM "ejercicio4.dtd">
<videoclub>
    <factura numero="F7">
        <datosClientes ID="12">
            <nombre>Jose Miguel</nombre>
            <primerApellido>Cabrera</primerApellido>
            <segundoApellido>Sampedro</segundoApellido>
            <DNI>12345678C</DNI>
            <telefono>666666666</telefono>
        </datosClientes>
        <datosTicket>
            <resguardo>
                <formaPago>Tarjeta</formaPago>
                <total>56</total>
            </resguardo>
            <alquiler>
                <fechaDevolucion>
                    <dia>12</dia>
                    <mes>2</mes>
                    <anyo>1999</anyo>
                </fechaDevolucion>
                <pelicula id="1" valoracion="5">
                <titulo>Lo que el viento se llevo</titulo>
                <genero>Belica</genero>
                <duracion>120</duracion>
                <actor>Amanda Young</actor>
                <actor>Leonardo DiCaprio</actor>
                <actor>Viggo Mortensen</actor>
                </pelicula>
            </alquiler>
            <compra>
                <DVD extras="N">
                    <titulo>El se√±or de los anillos</titulo>
                    <fechaSalida>
                        <dia>21</dia>
                        <mes>12</mes>
                        <anyo>2005</anyo>
                    </fechaSalida>
                </DVD>
                <cinta>
                    <formato rebobinado="S"></formato>
                </cinta>
            </compra>
        </datosTicket>
    </factura>
</videoclub>
