=== W3irdev/DAW/lenguajeMarcas/DTD/tiendas/tiendas.dtd
<!ELEMENT tiendas (tienda)+>
<!ELEMENT tienda (nombre+, direccion+, distribuidor?,movil+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT distribuidor (#PCDATA)>
<!ELEMENT movil (marca, caracteristicas)>
<!ATTLIST movil codigo ID #REQUIRED>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT caracteristicas (#PCDATA)>

=== W3irdev/DAW/lenguajeMarcas/DTD/tiendas/tienda2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tiendas SYSTEM "tiendas.dtd">

<tiendas>
    <tienda>
        <nombre>LatiendaMovil</nombre>
        <direccion>C/DOndevenden, 24</direccion>
        <distribuidor></distribuidor>
        <distribuidor></distribuidor>
        <movil>
            <codigo>M355</codigo>
            <marca>Alcatel</marca>
            <caracteristicas>Snapdragon Lagartija</caracteristicas>
        </movil>


    </tienda>
</tiendas>

=== W3irdev/DAW/lenguajeMarcas/DTD/tiendas/tienda1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tiendas SYSTEM "tiendas.dtd">

<tiendas>
    <tienda>
        <nombre>LatiendaMovil</nombre>
        <direccion>C/DOndevenden, 24</direccion>
        <distribuidor></distribuidor>
        <movil codigo="M355">
            <marca>Alcatel</marca>
            <caracteristicas>Snapdragon Lagartija</caracteristicas>
        </movil>


    </tienda>
</tiendas>
